title:   Helen Ma
logo: "/images/Profile.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  I'm passionate about transforming data to interactive stories and is looking for job opportunities in Data Analytics.
  <br><br>
  Perceptive and logical professional with proven ability to communicate with both technical professionals and end users to identify and translate business requirements. Proven ability to work with talented professionals to develop valuable process solutions to meet business objectives. 
  <br><br>
  <a href="www.linkedin.com/in/helen-huier-ma">View My LinkedIn Profile</a>
  <br><br>
  <a href="https://public.tableau.com/app/profile/helen.huier.ma">View My Tableau Work Samples</a>
  <br><br>
  <a href="https://www.notion.so/helen-huier-ma/About-Me-Helen-Ma-2858d74e45f3436a90c20f124d7da584">View My Notion Portfolios</a>
  
theme: jekyll-theme-minimal
 
